spring.application.name=tradeservice

spring.datasource.url=jdbc:mysql://localhost:3306/authdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration


# Expose the required Actuator endpoints (Health, Info, Metrics, Prometheus)
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Always display full health details (e.g., disk space, DB connections) instead of a simple "UP" status
management.endpoint.health.show-details=always

# Attach a common tag to all metrics so you can filter by this application name in Grafana
management.metrics.tags.application=trade-service

# Kafka Producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true

# Kafka Consumer
spring.kafka.consumer.group-id=energy-trading-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Outbox Settings
outbox.publisher.interval-ms=2000
outbox.publisher.max-retries=5



#redis

spring.data.redis.host=localhost
spring.data.redis.port=6379



# OAuth2 resource server disabled - authentication is handled by api-gateway
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
